# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fatorial.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(330, 70, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(110, 140, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_text.setFont(font)
        self.label_text.setObjectName("label_text")
        self.lineEdit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input.setGeometry(QtCore.QRect(110, 180, 251, 22))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.label_print = QtWidgets.QLabel(self.centralwidget)
        self.label_print.setGeometry(QtCore.QRect(110, 330, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_print.setFont(font)
        self.label_print.setText("")
        self.label_print.setObjectName("label_print")
        self.pushButton_Enviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Enviar.setGeometry(QtCore.QRect(110, 230, 93, 28))
        self.pushButton_Enviar.setObjectName("pushButton_Enviar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Fatorial"))
        self.label_text.setText(_translate("MainWindow", "Digite um número inteiro:"))
        self.pushButton_Enviar.setText(_translate("MainWindow", "Enviar"))
