# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'par_impar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(300, 60, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_numero = QtWidgets.QLabel(self.centralwidget)
        self.label_numero.setGeometry(QtCore.QRect(180, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_numero.setFont(font)
        self.label_numero.setObjectName("label_numero")
        self.lineEdit_numero = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_numero.setGeometry(QtCore.QRect(180, 190, 221, 22))
        self.lineEdit_numero.setObjectName("lineEdit_numero")
        self.pushButton_Enviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Enviar.setGeometry(QtCore.QRect(180, 240, 101, 31))
        self.pushButton_Enviar.setObjectName("pushButton_Enviar")
        self.label_resposta = QtWidgets.QLabel(self.centralwidget)
        self.label_resposta.setGeometry(QtCore.QRect(190, 320, 161, 71))
        self.label_resposta.setText("")
        self.label_resposta.setObjectName("label_resposta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Par ou Impar"))
        self.label_numero.setText(_translate("MainWindow", "Digite o número:"))
        self.pushButton_Enviar.setText(_translate("MainWindow", "Enviar"))
