# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'denyel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_instagram = QtWidgets.QLabel(self.centralwidget)
        self.label_instagram.setGeometry(QtCore.QRect(360, 340, 91, 71))
        self.label_instagram.setText("")
        self.label_instagram.setPixmap(QtGui.QPixmap("Imagens/instagram.png"))
        self.label_instagram.setScaledContents(True)
        self.label_instagram.setObjectName("label_instagram")
        self.label_whatsapp = QtWidgets.QLabel(self.centralwidget)
        self.label_whatsapp.setGeometry(QtCore.QRect(540, 320, 131, 101))
        self.label_whatsapp.setText("")
        self.label_whatsapp.setPixmap(QtGui.QPixmap("Imagens/whatsapp-logo-whatsapp-icon-whatsapp-transparent-free-png.webp"))
        self.label_whatsapp.setScaledContents(True)
        self.label_whatsapp.setObjectName("label_whatsapp")
        self.label_github = QtWidgets.QLabel(self.centralwidget)
        self.label_github.setGeometry(QtCore.QRect(160, 330, 91, 81))
        self.label_github.setText("")
        self.label_github.setPixmap(QtGui.QPixmap("Imagens/github.png"))
        self.label_github.setScaledContents(True)
        self.label_github.setObjectName("label_github")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 100, 231, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 60, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_perfil = QtWidgets.QLabel(self.centralwidget)
        self.label_perfil.setGeometry(QtCore.QRect(70, 100, 181, 171))
        self.label_perfil.setText("")
        self.label_perfil.setPixmap(QtGui.QPixmap("Imagens/perfil.png"))
        self.label_perfil.setScaledContents(True)
        self.label_perfil.setObjectName("label_perfil")
        self.pushButton_github = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_github.setGeometry(QtCore.QRect(160, 450, 93, 28))
        self.pushButton_github.setObjectName("pushButton_github")
        self.pushButton_instagram = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_instagram.setGeometry(QtCore.QRect(360, 450, 93, 28))
        self.pushButton_instagram.setObjectName("pushButton_instagram")
        self.pushButton_whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_whatsapp.setGeometry(QtCore.QRect(560, 450, 93, 28))
        self.pushButton_whatsapp.setObjectName("pushButton_whatsapp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sou um desenvolvedor em busca de aprimoramento e desafios para serem superados. Trabalhando com desenvolvimento web e desktop."))
        self.label_2.setText(_translate("MainWindow", "Denyel"))
        self.pushButton_github.setText(_translate("MainWindow", "Clicar"))
        self.pushButton_instagram.setText(_translate("MainWindow", "Clicar"))
        self.pushButton_whatsapp.setText(_translate("MainWindow", "Clicar"))
