# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 80, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 170, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(200, 170, 421, 22))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 220, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.radioButton_fem = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_fem.setGeometry(QtCore.QRect(200, 220, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_fem.setFont(font)
        self.radioButton_fem.setObjectName("radioButton_fem")
        self.radioButton_masc = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_masc.setGeometry(QtCore.QRect(320, 220, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_masc.setFont(font)
        self.radioButton_masc.setObjectName("radioButton_masc")
        self.checkBox_termo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_termo.setGeometry(QtCore.QRect(290, 320, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_termo.setFont(font)
        self.checkBox_termo.setObjectName("checkBox_termo")
        self.pushButton_apagar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_apagar.setGeometry(QtCore.QRect(260, 400, 93, 28))
        self.pushButton_apagar.setObjectName("pushButton_apagar")
        self.pushButton_enviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enviar.setGeometry(QtCore.QRect(390, 400, 93, 28))
        self.pushButton_enviar.setObjectName("pushButton_enviar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tela de Cadastro"))
        self.label_2.setText(_translate("MainWindow", "Nome:"))
        self.label_3.setText(_translate("MainWindow", "Sexo:"))
        self.radioButton_fem.setText(_translate("MainWindow", "Feminino"))
        self.radioButton_masc.setText(_translate("MainWindow", "Masculino"))
        self.checkBox_termo.setText(_translate("MainWindow", "Aceito os termos"))
        self.pushButton_apagar.setText(_translate("MainWindow", "Apagar"))
        self.pushButton_enviar.setText(_translate("MainWindow", "Enviar"))
