# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabuada.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(330, 60, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.lineEdit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input.setGeometry(QtCore.QRect(260, 170, 151, 22))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.label_digite = QtWidgets.QLabel(self.centralwidget)
        self.label_digite.setGeometry(QtCore.QRect(260, 120, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_digite.setFont(font)
        self.label_digite.setObjectName("label_digite")
        self.pushButton_enviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enviar.setGeometry(QtCore.QRect(260, 220, 93, 28))
        self.pushButton_enviar.setObjectName("pushButton_enviar")
        self.label_print = QtWidgets.QLabel(self.centralwidget)
        self.label_print.setGeometry(QtCore.QRect(250, 280, 381, 221))
        self.label_print.setText("")
        self.label_print.setObjectName("label_print")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Tabuada"))
        self.label_digite.setText(_translate("MainWindow", "Digite um número inteiro:"))
        self.pushButton_enviar.setText(_translate("MainWindow", "Enviar"))
