# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'somar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(250, 50, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_primeiro = QtWidgets.QLabel(self.centralwidget)
        self.label_primeiro.setGeometry(QtCore.QRect(160, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_primeiro.setFont(font)
        self.label_primeiro.setObjectName("label_primeiro")
        self.lineEdit_valor1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_valor1.setGeometry(QtCore.QRect(260, 150, 301, 22))
        self.lineEdit_valor1.setObjectName("lineEdit_valor1")
        self.lineEdit_valor2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_valor2.setGeometry(QtCore.QRect(260, 190, 301, 22))
        self.lineEdit_valor2.setText("")
        self.lineEdit_valor2.setObjectName("lineEdit_valor2")
        self.label_segundo = QtWidgets.QLabel(self.centralwidget)
        self.label_segundo.setGeometry(QtCore.QRect(160, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_segundo.setFont(font)
        self.label_segundo.setObjectName("label_segundo")
        self.label_resposta = QtWidgets.QLabel(self.centralwidget)
        self.label_resposta.setGeometry(QtCore.QRect(160, 290, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resposta.setFont(font)
        self.label_resposta.setText("")
        self.label_resposta.setObjectName("label_resposta")
        self.pushButton_Enviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Enviar.setGeometry(QtCore.QRect(350, 230, 101, 31))
        self.pushButton_Enviar.setObjectName("pushButton_Enviar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Somar dois números"))
        self.label_primeiro.setText(_translate("MainWindow", "Primeiro:"))
        self.label_segundo.setText(_translate("MainWindow", "Segundo:"))
        self.pushButton_Enviar.setText(_translate("MainWindow", "Enviar"))
