# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nome.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_Titulo.setGeometry(QtCore.QRect(130, 70, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Titulo.setFont(font)
        self.label_Titulo.setObjectName("label_Titulo")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(130, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.pushButton_Exibir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exibir.setGeometry(QtCore.QRect(320, 230, 111, 41))
        self.pushButton_Exibir.setObjectName("pushButton_Exibir")
        self.label_Resposta = QtWidgets.QLabel(self.centralwidget)
        self.label_Resposta.setGeometry(QtCore.QRect(130, 350, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Resposta.setFont(font)
        self.label_Resposta.setText("")
        self.label_Resposta.setObjectName("label_Resposta")
        self.lineEdit_Nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Nome.setGeometry(QtCore.QRect(290, 150, 221, 22))
        self.lineEdit_Nome.setObjectName("lineEdit_Nome")
        self.label_idade = QtWidgets.QLabel(self.centralwidget)
        self.label_idade.setGeometry(QtCore.QRect(130, 180, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_idade.setFont(font)
        self.label_idade.setObjectName("label_idade")
        self.lineEdit_idade = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_idade.setGeometry(QtCore.QRect(290, 190, 221, 22))
        self.lineEdit_idade.setObjectName("lineEdit_idade")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Titulo.setText(_translate("MainWindow", "Programa para exibir o nome digitado"))
        self.label_nome.setText(_translate("MainWindow", "Digite o nome:"))
        self.pushButton_Exibir.setText(_translate("MainWindow", "Exibir nome"))
        self.label_idade.setText(_translate("MainWindow", "Digite o idade:"))
